// THIS FILE IS GENERATED BY build-textures.js
// If npm run dev is active, as files / folders change inside the textures folder, this file will be regenerated
// Do not make changes here, they'll be blown away by the background watcher anyway

export const Textures = {
  "entity": {
    "hostile": {
      "burning skeleton": {
        "bskeleton": "/assets/textures/entity/hostile/burning skeleton/bskeleton.png",
        "bskeleton_attack": "/assets/textures/entity/hostile/burning skeleton/bskeleton_attack.png",
        "bskeleton_dead": "/assets/textures/entity/hostile/burning skeleton/bskeleton_dead.png",
        "bskeleton_die": "/assets/textures/entity/hostile/burning skeleton/bskeleton_die.png"
      },
      "burning zombie": {
        "bzombie": "/assets/textures/entity/hostile/burning zombie/bzombie.png",
        "bzombie_attack": "/assets/textures/entity/hostile/burning zombie/bzombie_attack.png",
        "bzombie_dead": "/assets/textures/entity/hostile/burning zombie/bzombie_dead.png",
        "bzombie_die": "/assets/textures/entity/hostile/burning zombie/bzombie_die.png"
      },
      "skeleton": {
        "skeleton": "/assets/textures/entity/hostile/skeleton/skeleton.png",
        "skeleton_attack": "/assets/textures/entity/hostile/skeleton/skeleton_attack.png",
        "skeleton_dead": "/assets/textures/entity/hostile/skeleton/skeleton_dead.png",
        "skeleton_die": "/assets/textures/entity/hostile/skeleton/skeleton_die.png"
      },
      "spider": {
        "spider": "/assets/textures/entity/hostile/spider/spider.png",
        "spider_dead": "/assets/textures/entity/hostile/spider/spider_dead.png",
        "spider_die": "/assets/textures/entity/hostile/spider/spider_die.png"
      },
      "zombie": {
        "zombie": "/assets/textures/entity/hostile/zombie/zombie.png",
        "zombie_attack": "/assets/textures/entity/hostile/zombie/zombie_attack.png",
        "zombie_dead": "/assets/textures/entity/hostile/zombie/zombie_dead.png",
        "zombie_die": "/assets/textures/entity/hostile/zombie/zombie_die.png"
      }
    },
    "passive": {
      "mooper": {
        "minimoop": "/assets/textures/entity/passive/mooper/minimoop.png",
        "moop": "/assets/textures/entity/passive/mooper/moop.png",
        "mooper": "/assets/textures/entity/passive/mooper/mooper.png",
        "omega_mooper": "/assets/textures/entity/passive/mooper/omega_mooper.png",
        "shaman_mooper": "/assets/textures/entity/passive/mooper/shaman_mooper.png"
      }
    }
  },
  "icons": {
    "dungeon": "/assets/textures/icons/dungeon.png"
  },
  "inventory": {
    "armor": {
      "arcticpelts_inventory": "/assets/textures/inventory/armor/arcticpelts_inventory.png",
      "armet_inventory": "/assets/textures/inventory/armor/armet_inventory.png",
      "bascinet_inventory": "/assets/textures/inventory/armor/bascinet_inventory.png",
      "chainmail_inventory": "/assets/textures/inventory/armor/chainmail_inventory.png",
      "corruptedarmor_inventory": "/assets/textures/inventory/armor/corruptedarmor_inventory.png",
      "crown_inventory": "/assets/textures/inventory/armor/crown_inventory.png",
      "goldarmor_inventory": "/assets/textures/inventory/armor/goldarmor_inventory.png",
      "greathelm_inventory": "/assets/textures/inventory/armor/greathelm_inventory.png",
      "helm_inventory": "/assets/textures/inventory/armor/helm_inventory.png",
      "leatherarmor_inventory": "/assets/textures/inventory/armor/leatherarmor_inventory.png",
      "loricasegmentata_inventory": "/assets/textures/inventory/armor/loricasegmentata_inventory.png",
      "nasalhelm_inventory": "/assets/textures/inventory/armor/nasalhelm_inventory.png",
      "ornatearmor_inventory": "/assets/textures/inventory/armor/ornatearmor_inventory.png",
      "ornatehelm_inventory": "/assets/textures/inventory/armor/ornatehelm_inventory.png",
      "platearmor_inventory": "/assets/textures/inventory/armor/platearmor_inventory.png",
      "vikinghelm_inventory": "/assets/textures/inventory/armor/vikinghelm_inventory.png"
    },
    "background": "/assets/textures/inventory/background.png",
    "charm": {
      "board": "/assets/textures/inventory/charm/board.png",
      "diamond": "/assets/textures/inventory/charm/diamond.png",
      "orb": "/assets/textures/inventory/charm/orb.png",
      "pebble": "/assets/textures/inventory/charm/pebble.png",
      "shamrock": "/assets/textures/inventory/charm/shamrock.png",
      "souljar": "/assets/textures/inventory/charm/souljar.png",
      "stick": "/assets/textures/inventory/charm/stick.png"
    },
    "null_inventory": "/assets/textures/inventory/null_inventory.png",
    "weapon": {
      "axe_inventory": "/assets/textures/inventory/weapon/axe_inventory.png",
      "ballista_inventory": "/assets/textures/inventory/weapon/ballista_inventory.png",
      "bloodcleaver_inventory": "/assets/textures/inventory/weapon/bloodcleaver_inventory.png",
      "bloodyclub_inventory": "/assets/textures/inventory/weapon/bloodyclub_inventory.png",
      "bombard_inventory": "/assets/textures/inventory/weapon/bombard_inventory.png",
      "bow_inventory": "/assets/textures/inventory/weapon/bow_inventory.png",
      "candlegun_inventory": "/assets/textures/inventory/weapon/candlegun_inventory.png",
      "chukonu_inventory": "/assets/textures/inventory/weapon/chukonu_inventory.png",
      "cleaver_inventory": "/assets/textures/inventory/weapon/cleaver_inventory.png",
      "club_inventory": "/assets/textures/inventory/weapon/club_inventory.png",
      "coldspear_inventory": "/assets/textures/inventory/weapon/coldspear_inventory.png",
      "coldsword_inventory": "/assets/textures/inventory/weapon/coldsword_inventory.png",
      "crossbow_inventory": "/assets/textures/inventory/weapon/crossbow_inventory.png",
      "dagger_inventory": "/assets/textures/inventory/weapon/dagger_inventory.png",
      "diamondsword_inventory": "/assets/textures/inventory/weapon/diamondsword_inventory.png",
      "eebeebsword_inventory": "/assets/textures/inventory/weapon/eebeebsword_inventory.png",
      "firespear_inventory": "/assets/textures/inventory/weapon/firespear_inventory.png",
      "firesword_inventory": "/assets/textures/inventory/weapon/firesword_inventory.png",
      "flail_inventory": "/assets/textures/inventory/weapon/flail_inventory.png",
      "goedendag_inventory": "/assets/textures/inventory/weapon/goedendag_inventory.png",
      "greataxe_inventory": "/assets/textures/inventory/weapon/greataxe_inventory.png",
      "greatsword_inventory": "/assets/textures/inventory/weapon/greatsword_inventory.png",
      "gun_inventory": "/assets/textures/inventory/weapon/gun_inventory.png",
      "halberd_inventory": "/assets/textures/inventory/weapon/halberd_inventory.png",
      "handcannon_inventory": "/assets/textures/inventory/weapon/handcannon_inventory.png",
      "hatchet_inventory": "/assets/textures/inventory/weapon/hatchet_inventory.png",
      "heavycrossbow_inventory": "/assets/textures/inventory/weapon/heavycrossbow_inventory.png",
      "iceegg_inventory": "/assets/textures/inventory/weapon/iceegg_inventory.png",
      "knife_inventory": "/assets/textures/inventory/weapon/knife_inventory.png",
      "kukri_inventory": "/assets/textures/inventory/weapon/kukri_inventory.png",
      "lightcrossbow_inventory": "/assets/textures/inventory/weapon/lightcrossbow_inventory.png",
      "longbow_inventory": "/assets/textures/inventory/weapon/longbow_inventory.png",
      "mace_inventory": "/assets/textures/inventory/weapon/mace_inventory.png",
      "morningstar_inventory": "/assets/textures/inventory/weapon/morningstar_inventory.png",
      "obsidianblade_inventory": "/assets/textures/inventory/weapon/obsidianblade_inventory.png",
      "pelletshooter_inventory": "/assets/textures/inventory/weapon/pelletshooter_inventory.png",
      "pickaxe_inventory": "/assets/textures/inventory/weapon/pickaxe_inventory.png",
      "poisonspear_inventory": "/assets/textures/inventory/weapon/poisonspear_inventory.png",
      "poisonsword_inventory": "/assets/textures/inventory/weapon/poisonsword_inventory.png",
      "scimitar_inventory": "/assets/textures/inventory/weapon/scimitar_inventory.png",
      "shotgun_inventory": "/assets/textures/inventory/weapon/shotgun_inventory.png",
      "sling_inventory": "/assets/textures/inventory/weapon/sling_inventory.png",
      "spear_inventory": "/assets/textures/inventory/weapon/spear_inventory.png",
      "spikedclub_inventory": "/assets/textures/inventory/weapon/spikedclub_inventory.png",
      "staffsling_inventory": "/assets/textures/inventory/weapon/staffsling_inventory.png",
      "stonebow_inventory": "/assets/textures/inventory/weapon/stonebow_inventory.png",
      "sword_inventory": "/assets/textures/inventory/weapon/sword_inventory.png",
      "trebuchet_inventory": "/assets/textures/inventory/weapon/trebuchet_inventory.png",
      "triflail_inventory": "/assets/textures/inventory/weapon/triflail_inventory.png"
    }
  },
  "item": {
    "helmet": {
      "base": "/assets/textures/item/helmet/base.png",
      "basinet": "/assets/textures/item/helmet/basinet.png",
      "crown": "/assets/textures/item/helmet/crown.png",
      "greathelm": "/assets/textures/item/helmet/greathelm.png",
      "nasalhelm": "/assets/textures/item/helmet/nasalhelm.png",
      "ornatehelm": "/assets/textures/item/helmet/ornatehelm.png",
      "skullcap": "/assets/textures/item/helmet/skullcap.png",
      "visorhelm": "/assets/textures/item/helmet/visorhelm.png"
    },
    "weapon": {
      "axe": "/assets/textures/item/weapon/axe.png",
      "axe_attack": "/assets/textures/item/weapon/axe_attack.png",
      "bow": "/assets/textures/item/weapon/bow.png",
      "bow_attack": "/assets/textures/item/weapon/bow_attack.png",
      "circle": "/assets/textures/item/weapon/circle.png",
      "club": "/assets/textures/item/weapon/club.png",
      "club_attack": "/assets/textures/item/weapon/club_attack.png",
      "crossbow": "/assets/textures/item/weapon/crossbow.png",
      "crossbow_attack": "/assets/textures/item/weapon/crossbow_attack.png",
      "greatsword": "/assets/textures/item/weapon/greatsword.png",
      "greatsword_attack": "/assets/textures/item/weapon/greatsword_attack.png",
      "gun": "/assets/textures/item/weapon/gun.png",
      "gun_attack": "/assets/textures/item/weapon/gun_attack.png",
      "hands": "/assets/textures/item/weapon/hands.png",
      "hands_attack": "/assets/textures/item/weapon/hands_attack.png",
      "hatchet": "/assets/textures/item/weapon/hatchet.png",
      "hatchet_attack": "/assets/textures/item/weapon/hatchet_attack.png",
      "knife": "/assets/textures/item/weapon/knife.png",
      "knife_attack": "/assets/textures/item/weapon/knife_attack.png",
      "spear": "/assets/textures/item/weapon/spear.png",
      "spear_attack": "/assets/textures/item/weapon/spear_attack.png",
      "sword": "/assets/textures/item/weapon/sword.png",
      "sword_attack": "/assets/textures/item/weapon/sword_attack.png"
    }
  },
  "object": {
    "mushroom": "/assets/textures/object/mushroom.png"
  },
  "particle": {
    "blaze": "/assets/textures/particle/blaze.png",
    "cold": "/assets/textures/particle/cold.png",
    "fire1": "/assets/textures/particle/fire1.png",
    "fire2": "/assets/textures/particle/fire2.png",
    "lightning": "/assets/textures/particle/lightning.png"
  },
  "player": {
    "base": "/assets/textures/player/base.png",
    "template": "/assets/textures/player/template.png"
  },
  "tiles": {
    "acid_green": "/assets/textures/tiles/acid_green.png",
    "acid_purple": "/assets/textures/tiles/acid_purple.png",
    "acid_yellow": "/assets/textures/tiles/acid_yellow.png",
    "blackstone": "/assets/textures/tiles/blackstone.png",
    "blood": "/assets/textures/tiles/blood.png",
    "bloodstone": "/assets/textures/tiles/bloodstone.png",
    "bonelr": "/assets/textures/tiles/bonelr.png",
    "boneud": "/assets/textures/tiles/boneud.png",
    "bricks": "/assets/textures/tiles/bricks.png",
    "burningstone": "/assets/textures/tiles/burningstone.png",
    "calcium": "/assets/textures/tiles/calcium.png",
    "dirt": "/assets/textures/tiles/dirt.png",
    "flesh": "/assets/textures/tiles/flesh.png",
    "fossil": "/assets/textures/tiles/fossil.png",
    "grass": "/assets/textures/tiles/grass.png",
    "gravel": "/assets/textures/tiles/gravel.png",
    "lava": "/assets/textures/tiles/lava.png",
    "rocks": "/assets/textures/tiles/rocks.png",
    "sand": "/assets/textures/tiles/sand.png",
    "slime": "/assets/textures/tiles/slime.png",
    "sprouts": "/assets/textures/tiles/sprouts.png",
    "stone": "/assets/textures/tiles/stone.png",
    "template": {
      "block_corner": "/assets/textures/tiles/template/block_corner.png",
      "block_end": "/assets/textures/tiles/template/block_end.png",
      "block_inside_corner": "/assets/textures/tiles/template/block_inside_corner.png",
      "block_inside_corner2": "/assets/textures/tiles/template/block_inside_corner2.png",
      "block_inside_corner3": "/assets/textures/tiles/template/block_inside_corner3.png",
      "block_inside_corner4": "/assets/textures/tiles/template/block_inside_corner4.png",
      "block_long": "/assets/textures/tiles/template/block_long.png",
      "block_middle": "/assets/textures/tiles/template/block_middle.png",
      "block_side": "/assets/textures/tiles/template/block_side.png",
      "block_single": "/assets/textures/tiles/template/block_single.png"
    },
    "water": "/assets/textures/tiles/water.png"
  }
}
