// THIS FILE IS GENERATED BY build-textures.js
// If npm run dev is active, as files / folders change inside the textures folder, this file will be regenerated
// Do not make changes here, they'll be blown away by the background watcher anyway

export const Textures = {
  "entity": {
    "hostile": {
      "burning_skeleton": {
        "bskeleton": "/assets/textures/entity/hostile/burning_skeleton/bskeleton.png",
        "bskeleton_attack": "/assets/textures/entity/hostile/burning_skeleton/bskeleton_attack.png",
        "bskeleton_dead": "/assets/textures/entity/hostile/burning_skeleton/bskeleton_dead.png",
        "bskeleton_die": "/assets/textures/entity/hostile/burning_skeleton/bskeleton_die.png"
      },
      "burning_zombie": {
        "bzombie": "/assets/textures/entity/hostile/burning_zombie/bzombie.png",
        "bzombie_attack": "/assets/textures/entity/hostile/burning_zombie/bzombie_attack.png",
        "bzombie_dead": "/assets/textures/entity/hostile/burning_zombie/bzombie_dead.png",
        "bzombie_die": "/assets/textures/entity/hostile/burning_zombie/bzombie_die.png"
      },
      "skeleton": {
        "skeleton": "/assets/textures/entity/hostile/skeleton/skeleton.png",
        "skeleton_attack": "/assets/textures/entity/hostile/skeleton/skeleton_attack.png",
        "skeleton_dead": "/assets/textures/entity/hostile/skeleton/skeleton_dead.png",
        "skeleton_die": "/assets/textures/entity/hostile/skeleton/skeleton_die.png"
      },
      "spider": {
        "spider": "/assets/textures/entity/hostile/spider/spider.png",
        "spider_dead": "/assets/textures/entity/hostile/spider/spider_dead.png",
        "spider_die": "/assets/textures/entity/hostile/spider/spider_die.png"
      },
      "zombie": {
        "zombie": "/assets/textures/entity/hostile/zombie/zombie.png",
        "zombie_attack": "/assets/textures/entity/hostile/zombie/zombie_attack.png",
        "zombie_dead": "/assets/textures/entity/hostile/zombie/zombie_dead.png",
        "zombie_die": "/assets/textures/entity/hostile/zombie/zombie_die.png"
      }
    },
    "passive": {
      "mooper": {
        "minimoop": "/assets/textures/entity/passive/mooper/minimoop.png",
        "moop": "/assets/textures/entity/passive/mooper/moop.png",
        "mooper": "/assets/textures/entity/passive/mooper/mooper.png",
        "omega_mooper": "/assets/textures/entity/passive/mooper/omega_mooper.png",
        "shaman_mooper": "/assets/textures/entity/passive/mooper/shaman_mooper.png"
      }
    }
  },
  "healthfull": "/assets/textures/healthfull.png",
  "icons": {
    "cs_logo": "/assets/textures/icons/cs_logo.png",
    "dungeon": "/assets/textures/icons/dungeon.png"
  },
  "inventory": {
    "chest": {
      "arcticpelts": "/assets/textures/inventory/chest/arcticpelts.png",
      "chainmail": "/assets/textures/inventory/chest/chainmail.png",
      "corruptedarmor": "/assets/textures/inventory/chest/corruptedarmor.png",
      "goldarmor": "/assets/textures/inventory/chest/goldarmor.png",
      "leatherarmor": "/assets/textures/inventory/chest/leatherarmor.png",
      "loricasegmentata": "/assets/textures/inventory/chest/loricasegmentata.png",
      "ornatearmor": "/assets/textures/inventory/chest/ornatearmor.png",
      "platearmor": "/assets/textures/inventory/chest/platearmor.png"
    },
    "feet": {
      "boots": "/assets/textures/inventory/feet/boots.png",
      "heavyboots": "/assets/textures/inventory/feet/heavyboots.png",
      "platedboots": "/assets/textures/inventory/feet/platedboots.png"
    },
    "hands": {
      "gloves": "/assets/textures/inventory/hands/gloves.png",
      "platedgloves": "/assets/textures/inventory/hands/platedgloves.png"
    },
    "head": {
      "armet": "/assets/textures/inventory/head/armet.png",
      "basinet": "/assets/textures/inventory/head/basinet.png",
      "crown": "/assets/textures/inventory/head/crown.png",
      "greathelm": "/assets/textures/inventory/head/greathelm.png",
      "helm": "/assets/textures/inventory/head/helm.png",
      "nasalhelm": "/assets/textures/inventory/head/nasalhelm.png",
      "ornatehelm": "/assets/textures/inventory/head/ornatehelm.png",
      "vikinghelm": "/assets/textures/inventory/head/vikinghelm.png"
    },
    "item": {
      "amber": "/assets/textures/inventory/item/amber.png",
      "amythest": "/assets/textures/inventory/item/amythest.png",
      "aquamarine": "/assets/textures/inventory/item/aquamarine.png",
      "board": "/assets/textures/inventory/item/board.png",
      "diamond": "/assets/textures/inventory/item/diamond.png",
      "emerald": "/assets/textures/inventory/item/emerald.png",
      "orb": "/assets/textures/inventory/item/orb.png",
      "pebble": "/assets/textures/inventory/item/pebble.png",
      "quartz": "/assets/textures/inventory/item/quartz.png",
      "ruby": "/assets/textures/inventory/item/ruby.png",
      "saphire": "/assets/textures/inventory/item/saphire.png",
      "shamrock": "/assets/textures/inventory/item/shamrock.png",
      "souljar": "/assets/textures/inventory/item/souljar.png",
      "stick": "/assets/textures/inventory/item/stick.png",
      "topaz": "/assets/textures/inventory/item/topaz.png"
    },
    "one_handed": {
      "bloodyclub": "/assets/textures/inventory/one_handed/bloodyclub.png",
      "club": "/assets/textures/inventory/one_handed/club.png",
      "coldsword": "/assets/textures/inventory/one_handed/coldsword.png",
      "dagger": "/assets/textures/inventory/one_handed/dagger.png",
      "diamondsword": "/assets/textures/inventory/one_handed/diamondsword.png",
      "eebeebsword": "/assets/textures/inventory/one_handed/eebeebsword.png",
      "firesword": "/assets/textures/inventory/one_handed/firesword.png",
      "flail": "/assets/textures/inventory/one_handed/flail.png",
      "hatchet": "/assets/textures/inventory/one_handed/hatchet.png",
      "iceegg": "/assets/textures/inventory/one_handed/iceegg.png",
      "knife": "/assets/textures/inventory/one_handed/knife.png",
      "kukri": "/assets/textures/inventory/one_handed/kukri.png",
      "mace": "/assets/textures/inventory/one_handed/mace.png",
      "morningstar": "/assets/textures/inventory/one_handed/morningstar.png",
      "obsidianblade": "/assets/textures/inventory/one_handed/obsidianblade.png",
      "pelletshooter": "/assets/textures/inventory/one_handed/pelletshooter.png",
      "pickaxe": "/assets/textures/inventory/one_handed/pickaxe.png",
      "poisonsword": "/assets/textures/inventory/one_handed/poisonsword.png",
      "scimitar": "/assets/textures/inventory/one_handed/scimitar.png",
      "sling": "/assets/textures/inventory/one_handed/sling.png",
      "spikedclub": "/assets/textures/inventory/one_handed/spikedclub.png",
      "sword": "/assets/textures/inventory/one_handed/sword.png",
      "triflail": "/assets/textures/inventory/one_handed/triflail.png"
    },
    "placeholders": {
      "bonus": "/assets/textures/inventory/placeholders/bonus.png",
      "chest": "/assets/textures/inventory/placeholders/chest.png",
      "feet": "/assets/textures/inventory/placeholders/feet.png",
      "hands": "/assets/textures/inventory/placeholders/hands.png",
      "head": "/assets/textures/inventory/placeholders/head.png",
      "mainhand": "/assets/textures/inventory/placeholders/mainhand.png",
      "offhand": "/assets/textures/inventory/placeholders/offhand.png"
    },
    "two_handed": {
      "axe": "/assets/textures/inventory/two_handed/axe.png",
      "ballista": "/assets/textures/inventory/two_handed/ballista.png",
      "bloodcleaver": "/assets/textures/inventory/two_handed/bloodcleaver.png",
      "bloodyclub": "/assets/textures/inventory/two_handed/bloodyclub.png",
      "bombard": "/assets/textures/inventory/two_handed/bombard.png",
      "bow": "/assets/textures/inventory/two_handed/bow.png",
      "candlegun": "/assets/textures/inventory/two_handed/candlegun.png",
      "chukonu": "/assets/textures/inventory/two_handed/chukonu.png",
      "cleaver": "/assets/textures/inventory/two_handed/cleaver.png",
      "club": "/assets/textures/inventory/two_handed/club.png",
      "coldspear": "/assets/textures/inventory/two_handed/coldspear.png",
      "coldsword": "/assets/textures/inventory/two_handed/coldsword.png",
      "crossbow": "/assets/textures/inventory/two_handed/crossbow.png",
      "dagger": "/assets/textures/inventory/two_handed/dagger.png",
      "diamondsword": "/assets/textures/inventory/two_handed/diamondsword.png",
      "eebeebsword": "/assets/textures/inventory/two_handed/eebeebsword.png",
      "firespear": "/assets/textures/inventory/two_handed/firespear.png",
      "firesword": "/assets/textures/inventory/two_handed/firesword.png",
      "flail": "/assets/textures/inventory/two_handed/flail.png",
      "goedendag": "/assets/textures/inventory/two_handed/goedendag.png",
      "greataxe": "/assets/textures/inventory/two_handed/greataxe.png",
      "greatsword": "/assets/textures/inventory/two_handed/greatsword.png",
      "gun": "/assets/textures/inventory/two_handed/gun.png",
      "halberd": "/assets/textures/inventory/two_handed/halberd.png",
      "handcannon": "/assets/textures/inventory/two_handed/handcannon.png",
      "hatchet": "/assets/textures/inventory/two_handed/hatchet.png",
      "heavycrossbow": "/assets/textures/inventory/two_handed/heavycrossbow.png",
      "iceegg": "/assets/textures/inventory/two_handed/iceegg.png",
      "knife": "/assets/textures/inventory/two_handed/knife.png",
      "kukri": "/assets/textures/inventory/two_handed/kukri.png",
      "lightcrossbow": "/assets/textures/inventory/two_handed/lightcrossbow.png",
      "longbow": "/assets/textures/inventory/two_handed/longbow.png",
      "mace": "/assets/textures/inventory/two_handed/mace.png",
      "morningstar": "/assets/textures/inventory/two_handed/morningstar.png",
      "obsidianblade": "/assets/textures/inventory/two_handed/obsidianblade.png",
      "pelletshooter": "/assets/textures/inventory/two_handed/pelletshooter.png",
      "pickaxe": "/assets/textures/inventory/two_handed/pickaxe.png",
      "poisonspear": "/assets/textures/inventory/two_handed/poisonspear.png",
      "poisonsword": "/assets/textures/inventory/two_handed/poisonsword.png",
      "scimitar": "/assets/textures/inventory/two_handed/scimitar.png",
      "shotgun": "/assets/textures/inventory/two_handed/shotgun.png",
      "sling": "/assets/textures/inventory/two_handed/sling.png",
      "spear": "/assets/textures/inventory/two_handed/spear.png",
      "spikedclub": "/assets/textures/inventory/two_handed/spikedclub.png",
      "staffsling": "/assets/textures/inventory/two_handed/staffsling.png",
      "stonebow": "/assets/textures/inventory/two_handed/stonebow.png",
      "sword": "/assets/textures/inventory/two_handed/sword.png",
      "trebuchet": "/assets/textures/inventory/two_handed/trebuchet.png",
      "triflail": "/assets/textures/inventory/two_handed/triflail.png"
    }
  },
  "item": {
    "circle": "/assets/textures/item/circle.png",
    "head": {
      "armet": "/assets/textures/item/head/armet.png",
      "base": "/assets/textures/item/head/base.png",
      "basinet": "/assets/textures/item/head/basinet.png",
      "crown": "/assets/textures/item/head/crown.png",
      "greathelm": "/assets/textures/item/head/greathelm.png",
      "helm": "/assets/textures/item/head/helm.png",
      "nasalhelm": "/assets/textures/item/head/nasalhelm.png",
      "ornatehelm": "/assets/textures/item/head/ornatehelm.png",
      "vikinghelm": "/assets/textures/item/head/vikinghelm.png",
      "visorhelm": "/assets/textures/item/head/visorhelm.png"
    },
    "weapon": {
      "axe": "/assets/textures/item/weapon/axe.png",
      "bow": "/assets/textures/item/weapon/bow.png",
      "club": "/assets/textures/item/weapon/club.png",
      "crossbow": "/assets/textures/item/weapon/crossbow.png",
      "greatsword": "/assets/textures/item/weapon/greatsword.png",
      "gun": "/assets/textures/item/weapon/gun.png",
      "hands": "/assets/textures/item/weapon/hands.png",
      "hatchet": "/assets/textures/item/weapon/hatchet.png",
      "knife": "/assets/textures/item/weapon/knife.png",
      "spear": "/assets/textures/item/weapon/spear.png",
      "sword": "/assets/textures/item/weapon/sword.png"
    },
    "weapon_attacks": {
      "axe_attack": "/assets/textures/item/weapon_attacks/axe_attack.png",
      "bow_attack": "/assets/textures/item/weapon_attacks/bow_attack.png",
      "club_attack": "/assets/textures/item/weapon_attacks/club_attack.png",
      "crossbow_attack": "/assets/textures/item/weapon_attacks/crossbow_attack.png",
      "greatsword_attack": "/assets/textures/item/weapon_attacks/greatsword_attack.png",
      "gun_attack": "/assets/textures/item/weapon_attacks/gun_attack.png",
      "hands_attack": "/assets/textures/item/weapon_attacks/hands_attack.png",
      "hatchet_attack": "/assets/textures/item/weapon_attacks/hatchet_attack.png",
      "knife_attack": "/assets/textures/item/weapon_attacks/knife_attack.png",
      "spear_attack": "/assets/textures/item/weapon_attacks/spear_attack.png",
      "sword_attack": "/assets/textures/item/weapon_attacks/sword_attack.png"
    }
  },
  "object": {
    "mushroom": "/assets/textures/object/mushroom.png"
  },
  "particle": {
    "blaze": "/assets/textures/particle/blaze.png",
    "cold": "/assets/textures/particle/cold.png",
    "fire1": "/assets/textures/particle/fire1.png",
    "fire2": "/assets/textures/particle/fire2.png",
    "lightning": "/assets/textures/particle/lightning.png"
  },
  "player": {
    "base": "/assets/textures/player/base.png",
    "template": "/assets/textures/player/template.png"
  },
  "tiles": {
    "acid_green": "/assets/textures/tiles/acid_green.png",
    "acid_purple": "/assets/textures/tiles/acid_purple.png",
    "acid_yellow": "/assets/textures/tiles/acid_yellow.png",
    "blackstone": "/assets/textures/tiles/blackstone.png",
    "blood": "/assets/textures/tiles/blood.png",
    "bloodstone": "/assets/textures/tiles/bloodstone.png",
    "bonelr": "/assets/textures/tiles/bonelr.png",
    "boneud": "/assets/textures/tiles/boneud.png",
    "bricks": "/assets/textures/tiles/bricks.png",
    "burningstone": "/assets/textures/tiles/burningstone.png",
    "calcium": "/assets/textures/tiles/calcium.png",
    "dirt": "/assets/textures/tiles/dirt.png",
    "flesh": "/assets/textures/tiles/flesh.png",
    "fossil": "/assets/textures/tiles/fossil.png",
    "grass": "/assets/textures/tiles/grass.png",
    "gravel": "/assets/textures/tiles/gravel.png",
    "lava": "/assets/textures/tiles/lava.png",
    "rocks": "/assets/textures/tiles/rocks.png",
    "sand": "/assets/textures/tiles/sand.png",
    "slime": "/assets/textures/tiles/slime.png",
    "sprouts": "/assets/textures/tiles/sprouts.png",
    "stone": "/assets/textures/tiles/stone.png",
    "template": {
      "block_corner": "/assets/textures/tiles/template/block_corner.png",
      "block_end": "/assets/textures/tiles/template/block_end.png",
      "block_inside_corner": "/assets/textures/tiles/template/block_inside_corner.png",
      "block_inside_corner2": "/assets/textures/tiles/template/block_inside_corner2.png",
      "block_inside_corner3": "/assets/textures/tiles/template/block_inside_corner3.png",
      "block_inside_corner4": "/assets/textures/tiles/template/block_inside_corner4.png",
      "block_long": "/assets/textures/tiles/template/block_long.png",
      "block_middle": "/assets/textures/tiles/template/block_middle.png",
      "block_side": "/assets/textures/tiles/template/block_side.png",
      "block_single": "/assets/textures/tiles/template/block_single.png"
    },
    "water": "/assets/textures/tiles/water.png"
  }
}
