// THIS FILE IS GENERATED BY build-sounds.js
// If npm run dev is active, as files / folders change inside the sounds folder, this file will be regenerated
// Do not make changes here, they'll be blown away by the background watcher anyway

export const Sounds = {
  "abilities": {
    "Shoot": "/assets/sounds/abilities/Shoot.m4a"
  },
  "item": {
    "ItemDrop": "/assets/sounds/item/ItemDrop.m4a",
    "ItemEquip": "/assets/sounds/item/ItemEquip.m4a",
    "ItemPickup": "/assets/sounds/item/ItemPickup.m4a"
  }
}
