const ART_SCALE = 1.5
const BLOCK_SIZE = 32
const DEBUG = true
const INVENTORY_HEIGHT = 450
const INVENTORY_WIDTH = 400
const MINIMAP_HEIGHT = 300
const MINIMAP_SCALE = 0.15
const MINIMAP_WIDTH = 300
const BAG_SLOTS = 60

export {
  ART_SCALE,
  BLOCK_SIZE,
  DEBUG,
  INVENTORY_HEIGHT,
  INVENTORY_WIDTH,
  MINIMAP_HEIGHT,
  MINIMAP_SCALE,
  MINIMAP_WIDTH,
  BAG_SLOTS
}
