const DEBUG = true

const ART_SCALE = 1.5
const BLOCK_SIZE = 32
const MINIMAP_SCALE = 0.15
const INVENTORY_WIDTH = 400
const INVENTORY_HEIGHT = 600

export { ART_SCALE, BLOCK_SIZE, MINIMAP_SCALE, INVENTORY_WIDTH, INVENTORY_HEIGHT, DEBUG }