const DEBUG = true
const ART_SCALE = 1.5
const BLOCK_SIZE = 32
const MINIMAP_HEIGHT = 300
const MINIMAP_SCALE = 0.15
const MINIMAP_WIDTH = 300
const BAG_SLOTS = 60

export {
  ART_SCALE,
  BLOCK_SIZE,
  DEBUG,
  MINIMAP_HEIGHT,
  MINIMAP_SCALE,
  MINIMAP_WIDTH,
  BAG_SLOTS
}
